version: '3.8'

services:
  backtest:
    build: .
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    command: python run_me_hw7.py backtest
    environment:
      - PYTHONUNBUFFERED=1
      - MATPLOTLIB_BACKEND=Agg

  trader:
    build: .
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    command: python run_me_hw7.py live
    environment:
      - PYTHONUNBUFFERED=1
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
    restart: unless-stopped
