version: '3.8'

services:
  trainer:
    build: .
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    command: python run_me_hw7.py
    environment:
      - PYTHONUNBUFFERED=1
      - MATPLOTLIB_BACKEND=Agg

  trader:
    build: .
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    command: python live_trading.py
    environment:
      - PYTHONUNBUFFERED=1
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - MODEL_PATH=/app/models/cnn_trader.pth
    restart: unless-stopped
