class Position:
    def __init__(self, dict_: dict):
        if dict_ is None:
            dict_ = {}
        self.info = dict_.get('info', None)
        self.id = dict_.get('id', None)
        self.symbol = dict_.get('symbol', None)
        self.contracts = dict_.get('contracts', 0)
        self.contractSize = dict_.get('contractSize', None)
        self.unrealizedPnl = dict_.get('unrealizedPnl', None)
        self.leverage = dict_.get('leverage', None)
        self.liquidationPrice = dict_.get('liquidationPrice', None)
        self.collateral = dict_.get('collateral', None)
        self.notional = dict_.get('notional', None)
        self.markPrice = dict_.get('markPrice', None)
        self.entryPrice = dict_.get('entryPrice', None)
        self.timestamp = dict_.get('timestamp', None)
        self.initialMargin = dict_.get('initialMargin', None)
        self.initialMarginPercentage = dict_.get('initialMarginPercentage', None)
        self.maintenanceMargin = dict_.get('maintenanceMargin', None)
        self.maintenanceMarginPercentage = dict_.get('maintenanceMarginPercentage', None)
        self.marginRatio = dict_.get('marginRatio', None)
        self.datetime = dict_.get('datetime', None)
        self.marginMode = dict_.get('marginMode', None)
        self.marginType = dict_.get('marginType', None)
        side = dict_.get('side', 0)
        self.side = 1 if side == 'long' else -1 if side == 'short' else 0
        self.hedged = dict_.get('hedged', None)
        self.percentage = dict_.get('percentage', None)
        self.stopLossPrice = dict_.get('stopLossPrice', None)
        self.takeProfitPrice = dict_.get('takeProfitPrice', None)
